namespace SecureVideoApp
{
    partial class MainForm
    {
        /// <summary>
        /// Обов'язкова змінна конструктора.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Звільнити всі використовувані ресурси.
        /// </summary>
        /// <param name="disposing"> істинно, якщо керований ресурс повинен бути видалений; інакше хибно.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code automatically generated by the Windows Form Designer

        /// <summary>
        /// Необхідний метод для підтримки конструктора — не змінюйте 
        /// вміст цього методу за допомогою редактора коду.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainForm));
            btnSelectFile = new Button();
            btnEncrypt = new Button();
            btnDecrypt = new Button();
            txtLog = new TextBox();
            pbNoise = new PictureBox();
            lblNoise = new Label();
            lblLog = new Label();
            axWindowsMediaPlayer1 = new AxWMPLib.AxWindowsMediaPlayer();
            statusStrip1 = new StatusStrip();
            toolStripStatusLabel1 = new ToolStripStatusLabel();
            buttonInfo = new Button();
            ((System.ComponentModel.ISupportInitialize)pbNoise).BeginInit();
            ((System.ComponentModel.ISupportInitialize)axWindowsMediaPlayer1).BeginInit();
            statusStrip1.SuspendLayout();
            SuspendLayout();
            // 
            // btnSelectFile
            // 
            btnSelectFile.BackColor = SystemColors.GradientInactiveCaption;
            btnSelectFile.Location = new Point(453, 206);
            btnSelectFile.Margin = new Padding(4, 3, 4, 3);
            btnSelectFile.Name = "btnSelectFile";
            btnSelectFile.Size = new Size(233, 40);
            btnSelectFile.TabIndex = 0;
            btnSelectFile.Text = "Відкрити файл";
            btnSelectFile.UseVisualStyleBackColor = false;
            btnSelectFile.Click += BtnSelectFile_Click;
            // 
            // btnEncrypt
            // 
            btnEncrypt.BackColor = SystemColors.Control;
            btnEncrypt.Enabled = false;
            btnEncrypt.Location = new Point(453, 257);
            btnEncrypt.Margin = new Padding(4, 3, 4, 3);
            btnEncrypt.Name = "btnEncrypt";
            btnEncrypt.Size = new Size(233, 40);
            btnEncrypt.TabIndex = 1;
            btnEncrypt.Text = "Зашифрувати медіапоток";
            btnEncrypt.UseVisualStyleBackColor = false;
            btnEncrypt.Click += BtnEncrypt_Click;
            // 
            // btnDecrypt
            // 
            btnDecrypt.BackColor = SystemColors.Control;
            btnDecrypt.Enabled = false;
            btnDecrypt.Location = new Point(453, 303);
            btnDecrypt.Margin = new Padding(4, 3, 4, 3);
            btnDecrypt.Name = "btnDecrypt";
            btnDecrypt.Size = new Size(233, 40);
            btnDecrypt.TabIndex = 2;
            btnDecrypt.Text = "Розшифрувати";
            btnDecrypt.UseVisualStyleBackColor = false;
            btnDecrypt.Click += BtnDecrypt_Click;
            // 
            // txtLog
            // 
            txtLog.BackColor = Color.WhiteSmoke;
            txtLog.Font = new Font("Cascadia Code", 8.25F, FontStyle.Regular, GraphicsUnit.Point, 204);
            txtLog.Location = new Point(714, 30);
            txtLog.Margin = new Padding(4, 3, 4, 3);
            txtLog.Multiline = true;
            txtLog.Name = "txtLog";
            txtLog.ReadOnly = true;
            txtLog.ScrollBars = ScrollBars.Vertical;
            txtLog.Size = new Size(349, 315);
            txtLog.TabIndex = 3;
            // 
            // pbNoise
            // 
            pbNoise.BackColor = Color.Black;
            pbNoise.BorderStyle = BorderStyle.Fixed3D;
            pbNoise.Location = new Point(453, 28);
            pbNoise.Margin = new Padding(4, 3, 4, 3);
            pbNoise.Name = "pbNoise";
            pbNoise.Size = new Size(233, 172);
            pbNoise.SizeMode = PictureBoxSizeMode.StretchImage;
            pbNoise.TabIndex = 5;
            pbNoise.TabStop = false;
            // 
            // lblNoise
            // 
            lblNoise.AutoSize = true;
            lblNoise.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            lblNoise.Location = new Point(453, 10);
            lblNoise.Margin = new Padding(4, 0, 4, 0);
            lblNoise.Name = "lblNoise";
            lblNoise.Size = new Size(199, 15);
            lblNoise.TabIndex = 6;
            lblNoise.Text = "Візуалізація ентропії (Ciphertext):";
            // 
            // lblLog
            // 
            lblLog.AutoSize = true;
            lblLog.Location = new Point(714, 12);
            lblLog.Margin = new Padding(4, 0, 4, 0);
            lblLog.Name = "lblLog";
            lblLog.Size = new Size(147, 15);
            lblLog.TabIndex = 7;
            lblLog.Text = "Системний журнал подій";
            // 
            // axWindowsMediaPlayer1
            // 
            axWindowsMediaPlayer1.Enabled = true;
            axWindowsMediaPlayer1.Location = new Point(13, 12);
            axWindowsMediaPlayer1.Margin = new Padding(4, 3, 4, 3);
            axWindowsMediaPlayer1.Name = "axWindowsMediaPlayer1";
            axWindowsMediaPlayer1.OcxState = (AxHost.State)resources.GetObject("axWindowsMediaPlayer1.OcxState");
            axWindowsMediaPlayer1.Size = new Size(418, 333);
            axWindowsMediaPlayer1.TabIndex = 8;
            // 
            // statusStrip1
            // 
            statusStrip1.Items.AddRange(new ToolStripItem[] { toolStripStatusLabel1 });
            statusStrip1.Location = new Point(0, 365);
            statusStrip1.Name = "statusStrip1";
            statusStrip1.Size = new Size(1079, 22);
            statusStrip1.TabIndex = 9;
            statusStrip1.Text = "statusStrip1";
            // 
            // toolStripStatusLabel1
            // 
            toolStripStatusLabel1.Name = "toolStripStatusLabel1";
            toolStripStatusLabel1.Size = new Size(0, 17);
            // 
            // buttonInfo
            // 
            buttonInfo.BackColor = SystemColors.ControlLight;
            buttonInfo.BackgroundImageLayout = ImageLayout.Center;
            buttonInfo.Cursor = Cursors.Help;
            buttonInfo.Location = new Point(1044, 7);
            buttonInfo.Name = "buttonInfo";
            buttonInfo.Size = new Size(19, 20);
            buttonInfo.TabIndex = 10;
            buttonInfo.Text = "?";
            buttonInfo.UseVisualStyleBackColor = false;
            buttonInfo.Click += button1_Click;
            // 
            // MainForm
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(1079, 387);
            Controls.Add(buttonInfo);
            Controls.Add(statusStrip1);
            Controls.Add(axWindowsMediaPlayer1);
            Controls.Add(lblLog);
            Controls.Add(lblNoise);
            Controls.Add(pbNoise);
            Controls.Add(txtLog);
            Controls.Add(btnDecrypt);
            Controls.Add(btnEncrypt);
            Controls.Add(btnSelectFile);
            FormBorderStyle = FormBorderStyle.FixedSingle;
            MaximizeBox = false;
            Name = "MainForm";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Магістерська робота: Прототип додатку для шифрування медіапотоків (з використанням Curve25519 + ChaCha20)";
            ((System.ComponentModel.ISupportInitialize)pbNoise).EndInit();
            ((System.ComponentModel.ISupportInitialize)axWindowsMediaPlayer1).EndInit();
            statusStrip1.ResumeLayout(false);
            statusStrip1.PerformLayout();
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        // Оголошення елементів управління
        private System.Windows.Forms.Button btnSelectFile;
        private System.Windows.Forms.Button btnEncrypt;
        private System.Windows.Forms.Button btnDecrypt;
        private System.Windows.Forms.TextBox txtLog;
        private System.Windows.Forms.PictureBox pbNoise;
        private System.Windows.Forms.Label lblNoise;
        private System.Windows.Forms.Label lblLog;
        private AxWMPLib.AxWindowsMediaPlayer axWindowsMediaPlayer1;
        private System.Windows.Forms.StatusStrip statusStrip1;
        private System.Windows.Forms.ToolStripStatusLabel toolStripStatusLabel1;
        private Button buttonInfo;
    }
}